export const ADD_URGENCES = 'ADD_URGENCES';
export const GET_URGENCES = 'GET_URGENCES';
export const DELETE_CONTACT = 'DELETE_CONTACT';
export const URGENCE_ERROR = 'URGENCE_ERROR';
export const SET_CURRENT = 'SET_CURRENT ';
export const CLEAR_CURRENT = 'CLEAR_CURRENT ';
export const UPDATE_URGENCE = 'UPDATE_URGENCE ';
export const CLEAR_FILTER = 'CLEAR_FILTER ';
export const DELETE_URGENCE = 'DELETE_URGENCE ';
export const DELETE_ERROR = 'DELETE_ERROR ';
export const CLEAR_URGENCES = 'CLEAR_URGENCES';

export const URGENCE_ID = 'URGENCE_ERROR';
export const ERROR_ID = 'ERROR_ID';



export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const USER_LOADED= 'USER_LOADED';;
export const REGISTER_FAIL= 'REGISTER_FAIL';
export const LOGIN_SUCCESS= 'LOGIN_SUCCESS';
export const LOGIN_FAIL= 'LOGIN_FAIL';
export const LOGOUT= 'LOGOUT';
export const FILTER_URGENCES= 'FILTER_URGENCES';
export const AUTH_ERROR ='AUTH_ERROR';